// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc3467.Robot3;
    
import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

import java.util.Vector;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static SpeedController driveBaseSpeedController1;
    public static SpeedController driveBaseSpeedController2;
    public static SpeedController driveBaseSpeedController3;
    public static SpeedController driveBaseSpeedController4;
    public static RobotDrive driveBaseRobotDrive41;
    public static SpeedController elevatorElevatorControler;
    public static SpeedController conveyorSpeedController1;
    public static double brownOutRoboRioVoltage;
    public static PowerDistributionPanel brownOutPDP;
    public static DigitalOutput brownOutDigitulOutput1;
    public static Solenoid conveyorBrakeSolenoid1;
    public static Solenoid elevatorBrakeSolenoid1;
	public static Compressor elevatorBrakeCompressor;

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        driveBaseSpeedController1 = new Talon(0);
        LiveWindow.addActuator("Drive Base", "Speed Controller 1", (Talon) driveBaseSpeedController1);
        
        driveBaseSpeedController2 = new Talon(1);
        LiveWindow.addActuator("Drive Base", "Speed Controller 2", (Talon) driveBaseSpeedController2);
        
        driveBaseSpeedController3 = new Talon(2);
        LiveWindow.addActuator("Drive Base", "Speed Controller 3", (Talon) driveBaseSpeedController3);
        
        driveBaseSpeedController4 = new Talon(3);
        LiveWindow.addActuator("Drive Base", "Speed Controller 4", (Talon) driveBaseSpeedController4);
        
        driveBaseRobotDrive41 = new RobotDrive(driveBaseSpeedController1, driveBaseSpeedController2,
              driveBaseSpeedController3, driveBaseSpeedController4);
        
        driveBaseRobotDrive41.setSafetyEnabled(true);
        driveBaseRobotDrive41.setExpiration(0.1);
        driveBaseRobotDrive41.setSensitivity(0.5);
        driveBaseRobotDrive41.setMaxOutput(1.0);

        elevatorElevatorControler = new Talon(4);
        LiveWindow.addActuator("Elevator", "Elevator Controler", (Talon) elevatorElevatorControler);
        
        conveyorSpeedController1 = new Talon(5);
        LiveWindow.addActuator("Conveyor", "Speed Controller 1", (Talon) conveyorSpeedController1);
        
        brownOutDigitulOutput1 = new DigitalOutput(0);
        LiveWindow.addActuator("Brown Out", "Digitul Output 1", brownOutDigitulOutput1);
        
        conveyorBrakeSolenoid1 = new Solenoid(0, 0);
        LiveWindow.addActuator("Conveyor Brake", "Solenoid 1", conveyorBrakeSolenoid1);
        
        elevatorBrakeSolenoid1 = new Solenoid(0, 1);
        LiveWindow.addActuator("Elevator Brake", "Solenoid 1", elevatorBrakeSolenoid1);
        
        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
